create table if not exists questions (
  id bigint generated by default as identity primary key,
  topic text not null,
  subtopic text not null,
  question_text text not null,
  choices jsonb not null,
  correct_answer text not null,
  explanation text not null,
  wrong_answer_explanations jsonb not null,
  exam_trap text,
  memory_takeaway text,
  difficulty text default 'medium',
  source_type text default 'original',
  created_at timestamptz default now()
);

create table if not exists attempts (
  id bigint generated by default as identity primary key,
  question_id bigint references questions(id),
  selected_answer text,
  is_correct boolean,
  confidence text,
  mistake_type text,
  time_spent_seconds int,
  created_at timestamptz default now()
);

create table if not exists recommendations (
  id bigint generated by default as identity primary key,
  recommendation_text text not null,
  topic text,
  reason text,
  created_at timestamptz default now()
);
