export const sampleQuestions = [
  ['General Principles','Cash Flow','A client earns $120,000 and spends $90,000 annually. What is savings rate?',{A:'15%',B:'20%',C:'25%',D:'30%'},'C','Savings rate is 30,000/120,000 = 25%.'],
  ['General Principles','Net Worth','Assets are $800,000 and liabilities are $260,000. Net worth is:',{A:'$440,000',B:'$520,000',C:'$540,000',D:'$1,060,000'},'C','Net worth equals assets minus liabilities.'],
  ['Insurance','Life Insurance','A term policy is best described as:',{A:'Permanent cash-value coverage',B:'Coverage for a specified period',C:'Investment-only product',D:'Annuity contract'},'B','Term insurance covers a specific time period.'],
  ['Insurance','Disability','Which definition is generally most favorable to insured?',{A:'Any occupation',B:'Own occupation',C:'Modified occupation',D:'Transitional occupation'},'B','Own occupation pays if unable to perform own job duties.'],
  ['Investments','Risk','Which metric measures portfolio volatility?',{A:'Beta',B:'Sharpe ratio',C:'Standard deviation',D:'Yield to maturity'},'C','Standard deviation is dispersion of returns.'],
  ['Investments','Asset Allocation','A 30-year horizon generally supports:',{A:'Higher equity allocation',B:'Higher cash allocation',C:'All bonds',D:'No diversification needed'},'A','Long horizons can tolerate more volatility.'],
  ['Tax Planning','Capital Gains','Long-term capital gains apply when asset is held:',{A:'More than 6 months',B:'More than 1 year',C:'At least 30 days',D:'Any period'},'B','Long-term treatment starts after >1 year.'],
  ['Tax Planning','Deductions','Above-the-line deductions primarily reduce:',{A:'Tax credits',B:'Adjusted gross income',C:'Payroll tax',D:'State withholding'},'B','They reduce AGI before taxable income.'],
  ['Retirement Planning','401(k)','Catch-up contributions are generally available starting at age:',{A:'45',B:'50',C:'55',D:'59½'},'B','Most catch-up contributions start at age 50.'],
  ['Retirement Planning','Withdrawal Rate','Sequence risk is most relevant during:',{A:'Accumulation',B:'Distribution',C:'Education funding',D:'Mortgage underwriting'},'B','Poor early retirement returns can damage longevity.'],
  ['Estate Planning','Probate','A revocable living trust can help:',{A:'Eliminate all taxes',B:'Avoid probate for titled assets',C:'Increase Social Security',D:'Avoid creditors always'},'B','Trust-owned assets often bypass probate.'],
  ['Estate Planning','Beneficiary Designations','Which generally overrides a will?',{A:'Letter of instruction',B:'Beneficiary designation on account',C:'Household inventory',D:'Executor memo'},'B','Beneficiary forms control transfer for many accounts.'],
  ['Education Planning','529 Plans','Qualified withdrawals from a 529 are generally:',{A:'Taxable federally',B:'Tax-free federally',C:'Always penalized',D:'Only for graduate school'},'B','Qualified education withdrawals are federally tax-free.'],
  ['Education Planning','FAFSA','Parent assets in a student-owned custodial account are usually:',{A:'Ignored',B:'Assessed more heavily than parent-owned assets',C:'Tax-free always',D:'Converted to annuities automatically'},'B','Student assets often receive higher aid assessment.'],
  ['Ethics','Fiduciary Duty','Under fiduciary duty, CFP professionals must primarily:',{A:'Maximize product commissions',B:'Act in client best interest',C:'Guarantee investment returns',D:'Avoid written plans'},'B','Fiduciary standard centers on client interest.'],
  ['Ethics','Conflicts','Best practice for conflicts of interest is to:',{A:'Conceal immaterial conflicts',B:'Disclose and manage conflicts',C:'Ignore if client is sophisticated',D:'Delegate disclosure to custodian'},'B','Conflicts should be disclosed and mitigated.'],
  ['Investments','Bonds','When interest rates rise, existing bond prices usually:',{A:'Rise',B:'Fall',C:'Stay flat',D:'Double'},'B','Bond prices and rates are inversely related.'],
  ['Tax Planning','Roth IRA','Qualified Roth IRA distributions are generally:',{A:'Taxable and penalized',B:'Tax-free if requirements met',C:'Always ordinary income',D:'Only for first-home use'},'B','Roth qualified distributions are tax-free.'],
  ['Insurance','Property & Casualty','A higher deductible usually causes premiums to:',{A:'Increase',B:'Decrease',C:'Stay unchanged',D:'Become tax deductible'},'B','Higher deductible shifts more risk to insured, lowering premium.'],
  ['General Principles','Goal Prioritization','Best first step in prioritizing goals is:',{A:'Select highest return asset',B:'Clarify time horizon and importance',C:'Buy insurance immediately',D:'Rebalance quarterly'},'B','Planning starts with defining goals by urgency and importance.']
].map((q, idx) => ({
  id: idx + 1,
  topic: q[0],
  subtopic: q[1],
  question_text: q[2],
  choices: q[3],
  correct_answer: q[4],
  explanation: q[5],
  wrong_answer_explanations: { A: 'Not the best answer for CFP context.', B: 'Not the best answer for CFP context.', C: 'Not the best answer for CFP context.', D: 'Not the best answer for CFP context.' },
  exam_trap: 'Choosing a familiar but less precise concept.',
  memory_takeaway: `Remember the core rule for ${q[1]}.`,
}))
